name: ChronOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [debug, release]
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Environment Setup (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc make

    - name: Environment Setup (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install gcc make
      
    - name: Display compiler version
      run: |
        gcc --version
        make --version
    
    - name: Build ${{ matrix.build_type }}
      run: |
        make ${{ matrix.build_type }}
      
    - name: Build test ${{ matrix.build_type }}
      run: |
        make test_${{ matrix.build_type }}
      
    - name: Run tests
      run: |
        make run_test_${{ matrix.build_type }}
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          minisched*
          !**/*.o
        retention-days: 7

  code-analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck

    - name: Static Analysis
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem .
        
    - name: Check Formatting
      run: |
        if find . -name "*.c" -o -name "*.h" | xargs grep -l "	"; then
          echo "Files contain tabs instead of spaces"
          find . -name "*.c" -o -name "*.h" | xargs grep -l "	"
          exit 1
        fi
        
        if find . -name "*.c" -o -name "*.h" | xargs grep -l -E " +$"; then
          echo "Files contain trailing whitespace"
          find . -name "*.c" -o -name "*.h" | xargs grep -l -E " +$"
          exit 1
        fi

